trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  srcDirectory: '$(System.DefaultWorkingDirectory)/src'
  blogDirectory: '$(srcDirectory)/Blog'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(srcDirectory)'

- task: Npm@1
  displayName: install node modules
  inputs:
    command: 'install'
    workingDir: '$(blogDirectory)'

- task: CmdLine@2
  displayName: build assets
  inputs:
    script: 'npm run build-assets'
    workingDirectory: '$(blogDirectory)'

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    arguments: '--no-build --configuration $(buildConfiguration)'
    publishWebProjects: true
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(blogDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(blogDirectory)/bin/Release/netcoreapp2.1/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/release.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'