# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'

- task: DotNetCoreCLI@2
  displayName: tests
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/Blog.Tests'

- script: npm install
  displayName: npm install

- script: npm run build
  displayName: build assets

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/Blog/'