trigger: 
- master

variables:
  buildConfiguration: 'Release'
  srcDirectory: '$(System.DefaultWorkingDirectory)/src'
  blogDirectory: '$(srcDirectory)/Blog'

jobs:
- job: A
  displayName: 'Install OS'
  pool:
    vmImage: 'windows-2019'
- job: B
  displayName: 'Build & Test'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      workingDirectory: '$(srcDirectory)'
  - task: Npm@1
    displayName: install node modules
    inputs:
      command: 'install'
      workingDir: '$(blogDirectory)'
  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      workingDirectory: '$(srcDirectory)/Blog.Tests'
  - task: CmdLine@2
    displayName: E2E Tests
    inputs:
      script: 'npm run test:e2e'
      workingDirectory: '$(blogDirectory)'
- job: C1
  displayName: 'Drop Log on Failure'
  dependsOn: B
  condition: failed()
  steps:
  - script: echo THIS IS THE FAILURE
- job: C2
  displayName: 'Building Deploy Assets'
  dependsOn: B
  condition: succeeded()
  steps:
  - task: CmdLine@2
    displayName: build assets
    inputs:
      script: 'npm run build'
      workingDirectory: '$(blogDirectory)'