# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Blog.Test'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'build assets'

- script: dotnet publish --no-build --configuration $(buildConfiguration)
  displayName: 'publish'