trigger: 
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  srcDirectory: '$(System.DefaultWorkingDirectory)/src'
  blogDirectory: '$(srcDirectory)/Blog'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(srcDirectory)'

- task: Npm@1
  displayName: install node modules
  inputs:
    command: 'install'
    workingDir: '$(blogDirectory)'

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    workingDirectory: '$(srcDirectory)/Blog.Tests'

- task: CmdLine@2
  displayName: E2E Tests
  inputs:
    script: 'npm run test:e2e'
    workingDirectory: '$(blogDirectory)'

- task: CmdLine@2
  displayName: build assets
  inputs:
    script: 'npm run build'
    workingDirectory: '$(blogDirectory)'