trigger: 
- master

variables:
  buildConfiguration: 'Release'
  srcDirectory: '$(System.DefaultWorkingDirectory)\src'
  blogDirectory: '$(srcDirectory)\Blog'

pool:
  vmImage: 'windows-2019'
  
steps:
- task: Npm@1
  displayName: install node modules
  inputs:
    command: 'install'
    workingDir: '$(blogDirectory)'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(srcDirectory)'
- task: DotNetCoreCLI@2
  displayName: Unit Tests
  enabled: false
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    workingDirectory: '$(srcDirectory)/Blog.Tests'
- task: CmdLine@2
  displayName: E2E Tests
  continueOnError: true
  inputs:
    script: 'npm run test:e2e'
    workingDirectory: '$(blogDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'D:\a\1\s\src\Blog\cypress\screenshots\posting_spec.js'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    


- task: CmdLine@2
  displayName: build assets
  inputs:
    script: 'npm run build'
    workingDirectory: '$(blogDirectory)'
