trigger: 
- master

variables:
  buildConfiguration: 'Release'
  srcDirectory: '$(System.DefaultWorkingDirectory)\src'
  blogDirectory: '$(srcDirectory)\Blog'

pool:
  vmImage: 'windows-2019'
  
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(srcDirectory)'
- script: dir $(blogDirectory)
- task: Npm@1
  displayName: install node modules
  inputs:
    command: 'install'
    workingDir: '$(blogDirectory)'
- task: DotNetCoreCLI@2
  displayName: Unit Tests
  enabled: false
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    workingDirectory: '$(srcDirectory)/Blog.Tests'
- task: CmdLine@2
  displayName: E2E Tests
  continueOnError: true
  inputs:
    script: 'npm run test:e2e'
    workingDirectory: '$(blogDirectory)'
- script: dir $(blogDirectory)
- task: ArchiveFiles@2
  displayName: Archive Server Logs
  inputs:
    rootFolderOrFile: '$(blogDirectory)/log'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/logs.zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  displayName: Publish Logs
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Logs'
    publishLocation: 'Container'
- task: CmdLine@2
  displayName: build assets
  inputs:
    script: 'npm run build'
    workingDirectory: '$(blogDirectory)'
